In [19]:
import numpy as np

In [20]:
a = np.arange(15).reshape(3, 5)

In [21]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
a.shape

(3, 5)

In [23]:
a.ndim

2

In [24]:
help(np.ndim)

Help on function ndim in module numpy:

ndim(a)
    Return the number of dimensions of an array.
    
    Parameters
    ----------
    a : array_like
        Input array.  If it is not already an ndarray, a conversion is
        attempted.
    
    Returns
    -------
    number_of_dimensions : int
        The number of dimensions in `a`.  Scalars are zero-dimensional.
    
    See Also
    --------
    ndarray.ndim : equivalent method
    shape : dimensions of array
    ndarray.shape : dimensions of array
    
    Examples
    --------
    >>> np.ndim([[1,2,3],[4,5,6]])
    2
    >>> np.ndim(np.array([[1,2,3],[4,5,6]]))
    2
    >>> np.ndim(1)
    0



In [25]:
a.ndim

2

In [26]:
a.shape

(3, 5)

In [27]:
a.dtype

dtype('int64')

In [28]:
a.dtype.name

'int64'

In [29]:
a.size

15

In [30]:
type(a)

numpy.ndarray

In [31]:
b = np.array([6, 7, 8])

In [32]:
b

array([6, 7, 8])

In [33]:
type(b)

numpy.ndarray

In [34]:
b

array([6, 7, 8])